# 都道府県と市町村のマッピング
prefecture_city_map = {
    "東京都": ["東京", "八王子", "立川", "武蔵野", "三鷹"],
    "大阪府": ["大阪", "堺", "東大阪", "枚方", "豊中"],
    "北海道": ["札幌", "函館", "旭川", "室蘭", "釧路"],
    "愛知県": ["名古屋", "豊橋", "岡崎", "一宮", "瀬戸"],
    "福岡県": ["福岡", "北九州", "久留米", "飯塚", "大牟田"],
    "神奈川県": ["横浜", "川崎", "相模原", "横須賀", "藤沢"],
    "埼玉県": ["さいたま", "川越", "熊谷", "川口", "越谷"],
    "千葉県": ["千葉", "船橋", "松戸", "市川", "柏"]
}

# 日本語の都市名と英語の都市名のマッピング
city_name_map = {
    "東京": "Tokyo",
    "八王子": "Hachioji",
    "立川": "Tachikawa",
    "武蔵野": "Musashino",
    "三鷹": "Mitaka",
    "大阪": "Osaka",
    "堺": "Sakai",
    "東大阪": "Higashiosaka",
    "枚方": "Hirakata",
    "豊中": "Toyonaka",
    "札幌": "Sapporo",
    "函館": "Hakodate",
    "旭川": "Asahikawa",
    "室蘭": "Muroran",
    "釧路": "Kushiro",
    "名古屋": "Nagoya",
    "豊橋": "Toyohashi",
    "岡崎": "Okazaki",
    "一宮": "Ichinomiya",
    "瀬戸": "Seto",
    "福岡": "Fukuoka",
    "北九州": "Kitakyushu",
    "久留米": "Kurume",
    "飯塚": "Iizuka",
    "大牟田": "Omuta",
    "横浜": "Yokohama",
    "川崎": "Kawasaki",
    "相模原": "Sagamihara",
    "横須賀": "Yokosuka",
    "藤沢": "Fujisawa",
    "さいたま": "Saitama",
    "川越": "Kawagoe",
    "熊谷": "Kumagaya",
    "川口": "Kawaguchi",
    "越谷": "Koshigaya",
    "千葉": "Chiba",
    "船橋": "Funabashi",
    "松戸": "Matsudo",
    "市川": "Ichikawa",
    "柏": "Kashiwa"
}